### ISSUE TITLE
broken chai integration

### ISSUE THREAD

**Issue by pgherveou** [vesln/jack#7]
hi @vesln it looks like the the chai integrarion tests are failing
can you have a look at it, I havent been able to fix myself

**Comment by logicalparadox** [comment]
This library was last updated with the pre-`1.x` release of Chai and the plugin API has changed significantly since then. Your best bet currently is to use the Sinon integration for Chai until we have a chance to re-evaluate our options for a zero-dependency external mock/stub utility.

**Comment by pgherveou** [comment]
Yep thats what i did 
thks for the feedback Jake

**Comment by vesln** [comment]
Yeah, that's right. I'm looking forward to updating the lib when I get the chance to do some pair programming with @logicalparadox. Hopefully this will happen in 2 weeks or so.

@pgherveou thanks for opening the issue, I'll keep you posted!
